name: MobMechanics
version: 1.0.0
main: me.Lozke.MobMechanics
author: Lozke
description: Let us pray it does mob things.
api-version: 1.16
depend: [ProtocolLib, AgorianRifts, Loot]
softdepend: [PlayerMechanics]